
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: picstagram_development

test:
  <<: *default
  database: picstagram_test

production:
  <<: *default
  database: picstagram_production
  username: picstagram
  password: <%= ENV['PICSTAGRAM_DATABASE_PASSWORD'] %>
